pr: none
trigger: none

parameters:

- name: environment_name
  displayName: Select HDInsight Cluster Type to Reset the Password
  type: string
  values:
      - dev
      - uat
      - prod
  default: dev

- name: HDInsight_Type
  displayName: Select HDInsight Cluster Type
  type: string
  values:
      - HDSpark
      - HDKafka
  default: HDSpark

- name: node_type
  displayName: Select Node Type to Reset the Password
  type: string
  values:
      - HeadNode
      - WorkerNode
      - ZookeeperNode
  default: HeadNode


variables:  
  - name: connectedServiceName
    ${{ if eq(parameters.environment_name,'prod')}}: 
      value: cl-axso-az-devops-prod-spi
    ${{ else }}:
      value: cl-axso-az-devops-nonprod-spi
      
  - name: subscriptionId
    ${{ if eq(parameters.environment_name,'prod')}}: 
      value: [prod-subscriptionId]
    ${{ else }}:
      value: [nonprod-subscriptionId]
  
  - name: environment_prefix
    ${{ if eq(parameters.HDInsight_Type,'HDSpark')}}: 
      value: axso-nonprod-appl-forest
    ${{ else }}: 
      value: axsononprod-appl-forest

  - name: script_storageaccount_name
    ${{ if and(eq(parameters.environment_name,'dev'),eq(parameters.HDInsight_Type,'HDSpark'))}}: 
      value: [dev-spark-hdinsight-storage-account-name]
    ${{ elseif and(eq(parameters.environment_name,'dev'),eq(parameters.HDInsight_Type,'HDKafka'))}}: 
      value: [dev-kafka-hdinsight-storage-account-name]
    ${{ elseif and(eq(parameters.environment_name,'uat'),eq(parameters.HDInsight_Type,'HDSpark'))}}: 
      value: [uat-spark-hdinsight-storage-account-name]
    ${{ elseif and(eq(parameters.environment_name,'uat'),eq(parameters.HDInsight_Type,'HDKafka'))}}: 
      value: [dev-kafka-hdinsight-storage-account-name]
    ${{ elseif and(eq(parameters.environment_name,'prod'),eq(parameters.HDInsight_Type,'HDSpark'))}}: 
      value: [prod-spark-hdinsight-storage-account-name]
    ${{ elseif and(eq(parameters.environment_name,'prod'),eq(parameters.HDInsight_Type,'HDKafka'))}}: 
      value: [prod-kafka-hdinsight-storage-account-name]
    ${{ else }}: 
      value: [dev-spark-hdinsight-storage-account-name]
  
  - name: script_action_uri
    value: https://$(script_storageaccount_name).blob.core.windows.net/forest/password-update-bash-scrip.sh
      
  - name: keyvault_name
    ${{ if eq(parameters.environment_name,'dev')}}: 
        value: keyvault-name-dev
    ${{ elseif eq(parameters.environment_name,'uat')}}: 
        value: keyvault-name-uat
    ${{ elseif eq(parameters.environment_name,'prod')}}: 
        value: keyvault-name-prod

  - name: resource_group_name
    ${{ if eq(parameters.environment_name,'dev')}}: 
        value: dev-env-rg-name
    ${{ elseif eq(parameters.environment_name,'uat')}}: 
        value: uat-env-rg-name
    ${{ elseif eq(parameters.environment_name,'prod')}}: 
        value: prod-env-rg-name

  - name: keyvault_secret_name
    value: '$(environment_prefix)-${{parameters.environment_name}}-${{parameters.HDInsight_Type}}-${{parameters.node_type}}-pwd'

stages:
  
  - template: ../hd-insight-customscript/hd-insight-update-password-script.yml
    parameters:
      connectedServiceName:       $(connectedServiceName)
      SubscriptionId:             $(subscriptionId)
      resource_group_name:        $(resource_group_name)
      cluster_name:               $(environment_prefix)-${{lower(parameters.environment_name)}}-${{lower(parameters.HDInsight_Type)}}
      environment_name:           ${{lower(parameters.environment_name)}}_${{lower(parameters.HDInsight_Type)}}
      nodeType:                   ${{parameters.node_type}}
      keyvault_name:              $(keyvault_name)
      keyvault_secret_name: $(keyvault_secret_name)
      script_action_uri: $(script_action_uri)


      