parameters:
  - name: connectedServiceName
    displayName: "Select Service Connection"
    type: string

  - name: environment_name
    displayName: "environment name"
    type: string

  - name: SubscriptionId
    displayName: "Subscription Id"
    type: string

  - name: resource_group_name
    displayName: "Resource Group name"
    type: string

  - name: cluster_name
    displayName: "HD insight cluster Name"
    type: string
    
  - name: script_action_name
    displayName: "script_action name"
    default: "update-password"
    type: string

  - name: script_action_uri           
    default: ""
    type: string

  - name: scriptPath           
    default: "./forest/HDInsight-Patching/hd-insight-customscript/HDI-password-update.ps1"
    type: string
  
  - name: nodeType
    displayName: Select Node Type
    type: string
    default: ''

  - name: keyvault_name
    displayName: keyvault name
    type: string

  - name: keyvault_secret_name
    displayName: keyvault secret name
    type: string

stages:
  - stage: ${{parameters.environment_name}}
    # pool:
    #   vmImage: ubuntu-latest
    condition: and(succeeded(),not(startsWith(variables['Build.SourceBranch'], 'refs/pull')), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature')))
    jobs:
      - deployment: dev
        timeoutInMinutes: 0
        displayName: Deploy
        environment: ${{parameters.environment_name}}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  displayName: 'HDInsight Custom Script Action Setup'
                  inputs:
                      azureSubscription: "${{parameters.connectedServiceName}}"
                      ScriptType: 'FilePath'
                      ScriptPath: "${{parameters.scriptPath}}"
                      ScriptArguments:
                              -subscription_id "${{parameters.SubscriptionId}}" `
                              -resource_group_name "${{parameters.resource_group_name}}" `
                              -cluster_name "${{parameters.cluster_name}}" `
                              -script_action_name "${{parameters.script_action_name}}" `
                              -script_action_uri "${{parameters.script_action_uri}}" `
                              -nodeType '${{parameters.nodeType}}' `
                              -keyvaultName "${{parameters.keyvault_name}}" `
                              -keyvaultSecretName "${{parameters.keyvault_secret_name}}" `
                              -identifier $(Build.BuildNumber)
                      azurePowerShellVersion: 'LatestVersion'
                      workingDirectory: '$(System.DefaultWorkingDirectory)'
